In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

sentences = ['nice great best amazing', 'stop lies', 'pitiful nerd', 'excellent work', 'supreme quality', 'bad', 'highly respectable']
y_train = [1, 0, 0, 1, 1, 0, 1]

In [2]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
vocab_size = len(tokenizer.word_index) + 1 # 패딩을 고려하여 +1
print('단어 집합 :',vocab_size)

단어 집합 : 16


In [3]:
X_encoded = tokenizer.texts_to_sequences(sentences)
print('정수 인코딩 결과 :',X_encoded)

정수 인코딩 결과 : [[1, 2, 3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13], [14, 15]]


In [10]:
max_len = max(len(l) for l in X_encoded)
print('최대 길이 :',max_len)

최대 길이 : 4


In [9]:
X_train = pad_sequences(X_encoded, maxlen=max_len, padding='post')
y_train = np.array(y_train)
print('패딩 결과 :')
print(X_train)
print(y_train)

패딩 결과 :
[[ 1  2  3  4]
 [ 5  6  0  0]
 [ 7  8  0  0]
 [ 9 10  0  0]
 [11 12  0  0]
 [13  0  0  0]
 [14 15  0  0]]
[1 0 0 1 1 0 1]


In [8]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Flatten

embedding_dim = 4

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim, input_length=max_len))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
model.fit(X_train, y_train, epochs=100, verbose=2)

2023-02-12 20:34:18.147659: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:2d:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-02-12 20:34:18.516416: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:2d:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-02-12 20:34:18.516468: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:922] could not open file to read NUMA node: /sys/bus/pci/devices/0000:2d:00.0/numa_node
Your kernel may have been built without NUMA support.
2023-02-12 20:34:18.521240: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the app

Epoch 1/100
1/1 - 4s - loss: 0.6950 - acc: 0.4286 - 4s/epoch - 4s/step
Epoch 2/100
1/1 - 0s - loss: 0.6934 - acc: 0.4286 - 11ms/epoch - 11ms/step
Epoch 3/100
1/1 - 0s - loss: 0.6917 - acc: 0.4286 - 12ms/epoch - 12ms/step
Epoch 4/100
1/1 - 0s - loss: 0.6901 - acc: 0.5714 - 12ms/epoch - 12ms/step
Epoch 5/100
1/1 - 0s - loss: 0.6884 - acc: 0.7143 - 12ms/epoch - 12ms/step
Epoch 6/100
1/1 - 0s - loss: 0.6868 - acc: 0.7143 - 12ms/epoch - 12ms/step
Epoch 7/100
1/1 - 0s - loss: 0.6851 - acc: 0.7143 - 9ms/epoch - 9ms/step
Epoch 8/100
1/1 - 0s - loss: 0.6835 - acc: 0.8571 - 10ms/epoch - 10ms/step
Epoch 9/100
1/1 - 0s - loss: 0.6819 - acc: 0.8571 - 9ms/epoch - 9ms/step
Epoch 10/100
1/1 - 0s - loss: 0.6802 - acc: 0.8571 - 12ms/epoch - 12ms/step
Epoch 11/100
1/1 - 0s - loss: 0.6786 - acc: 0.8571 - 12ms/epoch - 12ms/step
Epoch 12/100
1/1 - 0s - loss: 0.6769 - acc: 0.8571 - 14ms/epoch - 14ms/step
Epoch 13/100
1/1 - 0s - loss: 0.6753 - acc: 0.8571 - 12ms/epoch - 12ms/step
Epoch 14/100
1/1 - 0s - loss: